import { Tutor, TutorApplication } from "./types";

export const MOCK_TUTORS: Tutor[] = [
  {
    id: "1",
    name: "Sarah Jenkins",
    avatar: "https://picsum.photos/200/200?random=1",
    subjects: ["Mathematics", "Physics", "Calculus"],
    rating: 3.8,
    reviewCount: 42,
    monthlyRate: 3000,
    location: "New York, NY",
    bio: "Certified math teacher with 10 years of experience in helping students prepare for SATs and college entrance exams.",
    experience: "10 Years - High School Teacher",
    isVerified: true,
  },
  {
    id: "2",
    name: "David Chen",
    avatar: "https://picsum.photos/200/200?random=2",
    subjects: ["English", "Literature", "Creative Writing"],
    rating: 4.5,
    reviewCount: 28,
    monthlyRate: 35,
    location: "Brooklyn, NY",
    bio: "Passionate about literature and writing. I help students find their voice and improve their essay writing skills.",
    experience: "5 Years - Private Tutor",
    isVerified: true,
  },
  {
    id: "3",
    name: "Emily Davis",
    avatar: "https://picsum.photos/200/200?random=3",
    subjects: ["Chemistry", "Biology"],
    rating: 4.9,
    reviewCount: 56,
    monthlyRate: 50,
    location: "Queens, NY",
    bio: "Med student offering specialized tutoring in sciences. I make complex concepts easy to understand.",
    experience: "3 Years - Peer Tutor",
    isVerified: false,
  },
  {
    id: "4",
    name: "Michael Ross",
    avatar: "https://picsum.photos/200/200?random=4",
    subjects: ["Computer Science", "Python", "React"],
    rating: 5.0,
    reviewCount: 15,
    monthlyRate: 60,
    location: "Remote",
    bio: "Senior Software Engineer teaching coding best practices and helping with bootcamps.",
    experience: "8 Years - Industry Professional",
    isVerified: true,
  },
  {
    id: "5",
    name: "Legese Girma",
    avatar: "https://picsum.photos/200/200?random=5",
    subjects: ["Computer Science", "Python", "React"],
    rating: 2.5,
    reviewCount: 5,
    monthlyRate: 2600,
    location: "Adama",
    bio: "Tutor for Elementary Students",
    experience: "2-Year Home to Home tutoring experience",
    isVerified: true,
  },
  {
    id: "6",
    name: "Bekan Deresa",
    avatar: "https://picsum.photos/200/200?random=6",
    subjects: ["Science", "Math", "Biology"],
    rating: 2.5,
    reviewCount: 2,
    monthlyRate: 1500,
    location: "Bishoftu",
    bio: "Tutor for Grade 1-12",
    experience: "1 year experience",
    isVerified: true,
  },
  {
    id: "7",
    name: "Kuma Diyana",
    avatar: "https://picsum.photos/200/200?random=7",
    subjects: ["Softwar Dev", "Java", "C++"],
    rating: 4.5,
    reviewCount: 5,
    monthlyRate: 4500,
    location: "Addis Ababa",
    bio: "Foundational Software Dev knowledge",
    experience: "5-Year experience in tech industry",
    isVerified: true,
  },
];

export const MOCK_APPLICATIONS: TutorApplication[] = [
  {
    id: "app_1",
    userId: "u_1",
    fullName: "John Doe",
    age: 28,
    phone: "555-0123",
    location: "Austin, TX",
    subjects: "History, Geography",
    experience: "3 years teaching assistant",
    bio: "Love history!",
    monthlyRate: 30,
    status: "pending",
    submittedAt: "2023-10-25",
  },
  {
    id: "app_2",
    userId: "u_2",
    fullName: "Jane Smith",
    age: 34,
    phone: "555-0199",
    location: "Seattle, WA",
    subjects: "Piano, Music Theory",
    experience: "10 years private lessons",
    bio: "Classical pianist.",
    monthlyRate: 50,
    status: "approved",
    submittedAt: "2023-10-20",
  },
];

export const SUBJECTS_LIST = [
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "English",
  "Spanish",
  "French",
  "History",
  "Computer Science",
  "Art",
  "Music",
];
